FROM python:3.10-slim

WORKDIR /app

# Install uv directly
RUN pip install uv

COPY requirements.txt .

# Execute uv system-wide installation
RUN uv pip install --system --no-cache -r requirements.txt

COPY . .

EXPOSE 8501
CMD ["streamlit", "run", "frontend/app.py", "--server.port", "8501", "--server.address", "0.0.0.0"]