FROM python:3.10-slim

WORKDIR /app

# Install uv
RUN pip install --no-cache-dir uv

# Install Python dependencies from project root
COPY requirements.txt .

RUN uv pip install --system --no-cache -r requirements.txt

# Copy the entire project into /app
COPY . .

EXPOSE 8501

CMD ["streamlit", "run", "frontend/app.py", "--server.port", "8501", "--server.address", "0.0.0.0"]